trigger:
- master

stages:
  - stage: build
    displayName: 'master-branch-build'

    #build jobs
    jobs: 
      - job: build
        pool:
          name: anime-app

        variables:
          buildConfiguration: 'Release'

        steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
            feedsToUse: 'select'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '--configuration $(BuildConfiguration)'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
  - stage: release
    displayName: 'deployment-release'
#release job
    jobs:
      - job: release
        pool:
              name: anime-app
        steps:
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'specific'
            itemPattern: '**/*.zip'
            downloadPath: '$(System.ArtifactsDirectory)'

        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'Avanade Delivery(3)(3eba6e29-3983-495b-a539-c3c4b43fb90c)'
            appType: 'webAppLinux'
            appName: 'KeneilAnimeApp'
            package: '$(System.DefaultWorkingDirectory)/'
            runtimeStack: 'DOTNETCORE|5.0'

        - task: SSH@0
          inputs:
            sshEndpoint: 'anime-app-service'
            runOptions: 'inline'
            inline: |
              if [ "$(docker ps -a | grep KeneilAnimeApp)" ]
              then
                  docker rm -f KeneilAnimeApp
              fi
              docker run -d -p 80:80 --name KeneilAnimeApp KeneilAnimeApp:latest
            readyTimeout: '20000'